version: '3.3'
services:
  database:
    build:
      context: ./docker/database
    restart: always
    env_file: variables.env
    environment:
      MYSQL_ROOT_PASSWORD: 'HY&p;}jInGF?3Uez=pk1;&1M^5%=31V2gx'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www
    networks:
      - backend
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www
    depends_on:
      - php
    networks:
      - backend
  cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./.:/project
    command: "php /project/test.php"
volumes:
  data:
networks:
  backend: