version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: '^v3J8e=p]o{dz+2ZbBC)0a42[/XJ<LXs]#'
      MYSQL_ROOT_PASSWORD: 'HY&p;}jInGF?3Uez=pk1;&1M^5%=31V2gx'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - data:/var/lib/mysql
  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www
    depends_on:
      - php
  test:
    build:
      context: ./docker/php-cli
    command: "php tests.php"
volumes:
  data: