version: '3.3'
services:
  database:
    build:
      context: ./docker/database
    restart: always
    env_file: variables.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www
    networks:
      - backend
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www
    depends_on:
      - php
    networks:
      - backend
  cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./.:/project
    command: "php /project/test.php"
volumes:
  data:
networks:
  backend: